# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install # will run `yarn install` command
    - uses: actions/upload-artifact@v3.1.1
      with: 
        name: build-artifact
        path: public/
    
  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v3.0.1
      with:
        name: build-artifact
        path: public
    
    - run: cd /home/runner/work/FeelGoodLandingPage/FeelGoodLandingPage/public
    - run: ls
    - run: yarn test

   # - run: npm ci
   # - run: npm run build --if-present
   # - run: npm test
